---
install_homebrew_ctf: true
install_homebrew_cask_ctf: true
install_homebrew_cask_extra: true
install_homebrew_cask_vm: true
configure_dock: true
add_trusted_root_cert: true

## Preferred shell (also login shell)
preferred_shell: /usr/local/bin/bash

user: "{{ ansible_user_id }}"
home_directory: "/Users/{{ user }}"
downloads_directory: "{{ home_directory }}/.ansible/downloads"

## .gitconfig variables
# git config user.name
# gitconfig_name: "Bits For Everyone"
# git config user.email
# gitconfig_email: "admin@bitsforeveryone.com"
# GitHub Username
# gitconfig_user: "bitsforeveryone"

homebrew_taps:
  - homebrew/cask-versions

homebrew_packages:
  - zsh
  - bash-completion
  - byobu
  - dark-mode   # Control the macOS dark mode from the command-line
  - dockutil    # Tool for managing dock items
  - gdb
  - git
  - git-lfs
  - go
  - ghi      # Work on GitHub issues on the command-line
  - grc      # Colorize logfiles and command output
  - htop
  - httpie   # User-friendly cURL replacement
  - hub      # Add GitHub support to git on the command-line
  - lynx
  - nmap
  - openssh
  - openssl
  - openvpn
  - p7zip
  - pv        # Monitor data's progress through a pipe
  - python
  - qemu
  - readline  # Library for command-line editing
  - socat
  - sqlite
  - tree      # Display directories as trees
  - vim
  - w3m
  - wget
# - cowsay

homebrew_cask_apps:
  - google-chrome
  - iterm2
  - slack
  - spectacle

homebrew_cask_vm:
  - docker
  - virtualbox
  - vmware-fusion
  - vmware-remote-console
  - vagrant

homebrew_cask_extra:
  - dropbox
  - firefox
  - google-backup-and-sync
  - lastpass
  - microsoft-remote-desktop-beta
  - powershell
  - sublime-text

homebrew_packages_ctf:
  - cutter
  - fcrackzip
  - foremost
  - hexedit
  - pngcheck
  - pwntools
  - radare2
  - unicorn
    
homebrew_cask_ctf:
  - idafree         # IDA Pro free
  - binary-ninja    # Binary-ninja demo

pip_packages:
  - numpy
  - requests
  - unicorn
  - virtualenvwrapper

gem_packages:
  - zsteg
