install_homebrew_ctf: false
install_homebrew_cask_extra: false

user:  "{{ ansible_user_id }}"
home_directory: "/Users/{{ user }}"
downloads_directory: "{{ home_directory }}/.ansible/downloads"

homebrew_taps:
  - caskroom/versions

homebrew_packages:
  - zsh
  - bash-completion
  - byobu
  - dark-mode # Control the macOS dark mode from the command-line
  - dockutil # Tool for managing dock items
  - gdb
  - git
  - git-lfs
  - go
  - ghi      # Work on GitHub issues on the command-line
  - grc      # Colorize logfiles and command output
  - httpie   # User-friendly cURL replacement
  - hub      # Add GitHub support to git on the command-line
  - lynx
  - nmap
  - openssh
  - openssl
  - openvpn
  - p7zip
  - pv       # Monitor data's progress through a pipe
  - python
  - qemu
  - readline # Library for command-line editing
  - socat 
  - sqlite
  - tree     # Display directories as trees
  - vim
  - w3m
  - wget
# - cowsay

homebrew_packages_ctf:
  - fcrackzip
  - foremost
  - hexedit
  - pngcheck
  - pwntools
  - radare2
  - unicorn
  - docker

homebrew_cask_apps:
  - dropbox
  - google-chrome
  - iterm2
  - microsoft-remote-desktop-beta
  - slack
  - spectacle
  - virtualbox
  - vmware-fusion
  - vmware-remote-console
# - firefox
# - sublime-text
 
homebrew_cask_extra: 
  - cutter
  - google-drive
  - lastpass
  - macvim
  - powershell
  - transmit
  - vagrant

pip_packages:
  - numpy
  - requests
  - unicorn
  - virtualenvwrapper

gem_packages:
  - zsteg
