---
os: osx
sudo: required
language: generic
# 10.13 (see  https://docs.travis-ci.com/user/reference/osx/ )
osx_image: xcode9.3


branches:
  only:
    - master

before_install:
  # check versions
  - which python
  - pip --version

  # Setup virtualenv
  # - sudo - pip install -U virtualenv
  # virtualenv --version
  # virtualenv .venv
  # source .venv/bin/activate
  
  # Install Ansible.
  - sudo -H pip install ansible
  - sudo -H pip install yamllint
  - sudo -H pip install ansible-lint
  
  # Check version
  - ansible --version
  - ansible-lint --version
  - yamllint --version

install:

  # Add ansible.cfg to pick up roles path.
  # - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

  # Add a hosts file.
  - sudo -H mkdir -p /etc/ansible
  - sudo -H touch /etc/ansible/hosts
  - "echo -e '[local]\nlocalhost ansible_connection=local' | sudo tee -a /etc/ansible/hosts > /dev/null"

script:
  # Lint all YAML files
  # - yamllint .

  # Lint the playbook
  ansible-lint -x ANSIBLE0013,ANSIBLE0004 main.yml

  # Check the role/playbook's syntax.
  - "ansible-playbook main.yml --syntax-check"

  # Test the playbook.
  - "travis_wait 30 ansible-playbook --extra-vars '{\"configure_sudoers\":\"false\"}' main.yml --skip-tags skipci"

  # Test the playbook's idempotence.
  - idempotence=$(mktemp)
  - "ansible-playbook main.yml --skip-tags skipci | tee -a ${idempotence}"
  - >
    tail ${idempotence}
    | grep -q 'failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
    | grep -q 'changed=0.*failed=0'
