---
os: osx
sudo: required
language: generic
# 10.13 (see  https://docs.travis-ci.com/user/reference/osx/ )
osx_image: xcode9.3


before_install:
  # Homebrew defaults to Python 3
  - brew update
  - export PATH=/usr/local/bin:/usr/local/sbin:$PATH
  - brew upgrade python
  - which python
  
  # Update pip
  # - sudo -H pip install -U pip
    
  # Install Ansible.
  - sudo -H pip install ansible
  
  # Check version
  - python --version
  - ansible --version
  - pip --version


install:

  # Add ansible.cfg to pick up roles path.
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

  # Add a hosts file.
  - sudo -H mkdir -p /etc/ansible
  - sudo -H touch /etc/ansible/hosts
  - "echo -e '[local]\nlocalhost ansible_connection=local' | sudo tee -a /etc/ansible/hosts > /dev/null"

script:
  # Check the role/playbook's syntax.
  - "ansible-playbook main.yml --syntax-check"

  # Test the playbook.
  - "travis_wait 30 ansible-playbook --extra-vars '{\"configure_sudoers\":\"false\"}' main.yml --skip-tags skipci"

  # Test the playbook's idempotence.
  - idempotence=$(mktemp)
  - "ansible-playbook main.yml --skip-tags skipci | tee -a ${idempotence}"
  - >
    tail ${idempotence}
    | grep -q 'failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
    #     | grep -q 'changed=0.*failed=0'
