---
- hosts: all 
  connection: local

  vars_files:
    - group_vars/dock.yml

  roles:
   - common
   - vmware
   - manticore
#  - brew-cask-extra
#  - ctf-packages
#  - role: ohmyzsh
#  - role: ida-pro-free
#    tags: ['IDA']
#  - role: BinaryNinja
#    tags: ['Binja']
#  - role: passwordless-sudo
#  - role: android
   - dotfiles

