---
- hosts: all
  connection: local

  vars_files:
    - group_vars/dock.yml

  roles:
   - common
   - vmware
   - brew-cask-extra
   - brew-cask-vm
   - ctf-packages
   - manticore
   - ohmyzsh
#  - role: ida-pro-demo
#    tags: ['IDA']
#  - role: BinaryNinja
#    tags: ['Binja']
   - role: passwordless-sudo
#  - role: android
   - dotfiles

