---
- hosts: all 
  connection: local

  vars_files:
    - group_vars/main.yml
    - group_vars/dock.yml

  roles:
   - common
   - vmware
   - manticore
   - dotfiles
#  - ohmyzsh
#  - passwordless-sudo
#  - android

