---
#  https://git.eecs.net/C3T/BinaryNinja.git
- src: git+https://git.eecs.net/C3T/BinaryNinja.git
  version: master
#  https://git.eecs.net/C3T/IDA-Pro-demo.git
- src: git+https://git.eecs.net/C3T/IDA-Pro-demo.git
  version: master
