---
- name: install homebrew packages ( CTF )
  homebrew:
    name: "{{ item }}"
    state: present
  with_items: "{{ homebrew_packages_ctf }}"
  when: install_homebrew_ctf
  tags:
    - ctf

- name: install hombrew cask apps ( CTF )
  homebrew_cask:
    name: "{{ item }}"
  with_items: "{{ homebrew_cask_ctf }}"
  when: install_homebrew_cask_ctf
  tags:
    - ctf
