---
- name:
  homebrew:
  name: "{{ $item }}" 
    state: present
  with_items: 
    - git 
    - zsh

- name: Backing up existing ~/.zshrc
  shell: if [ -f ~/.zshrc ]; then mv ~/.zshrc{,.orig}; fi
  when: installation|success
  sudo: no

- name: Cloning  oh-my-zsh
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh
    dest=~/.oh-my-zsh
  when: installation|success
  register: cloning
  sudo: no

- name: Creating new ~/.zshrc
  copy:
    src=~/.oh-my-zsh/templates/zshrc.zsh-template
    dest=~/.zshrc
  when: cloning|success
  sudo: no


- name: creating new ~/.zshrc
  template:
    src: zshrc.j2
    dest: "{{ item.home }}/.zshrc"
  with_items: "{{ ohmyzsh_users }}"
  tags: ohmyzsh_config

- name: Set zsh as default shell
  user: name=$user shell=/bin/zsh
