---
- name: install dependencies (git, zsh)
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - zsh
  register: installation

- name: Cloning  oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: ~/.oh-my-zsh
  register: cloning

- name: creating new ~/.zshrc
  template:
    src: zshrc.j2
    dest: "{{ item.home }}/.zshrc"
  with_items: "{{ ohmyzsh_users }}"

- name: read current shell
  shell: dscl . -read ~ UserShell | cut -d ' ' -f 2
  check_mode: no
  register: current_login_shell
  changed_when: False

- name: Set login shell (dscl)
  shell: dscl . -create "{{ home_directory }}"  UserShell "{{ preferred_shell }}"
  when: current_login_shell.stdout != preferred_shell
  become: true
