---

# Choose user who you want to install oh my zsh for
ohmyzsh_users:
  - username: root 
    usergroup: root
    home: /root

ohmyzsh_plugins: git brew colored-man-page colorize extract history httpie zsh-syntax-highlighting
