---
- name: install java
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
    - java8
  tags:
    - skipci
    - android

- name: install java development
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - ant
    - maven
    - gradle
  tags:
    - skipci
    - android

- name: install android development
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
    - java8
    - android-sdk
    - android-ndk
  tags:
    - skipci
    - android
