---
- name: install dependencies
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - virtualenv
    - virtualenvwrapper
  tags:
    - skipci

- name: install manticore in virtualenv
  pip:
    name: manticore
    virtualenv: ~/.virtualenvs/manticore
    virtualenv_site_packages: yes
    virtualenv_python: python2
