---
- name: Add eecs.net as trusted root authority
  command: security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain {{ role_path }}/files/eecsNET-CA.cer
  become: yes
  when: add_trusted_root_cert
  changed_when: False
  tags:
    - skipci

- name: add homebrew taps
  homebrew_tap:
    name: "{{ item }}"
    state: present
  with_items: "{{ homebrew_taps }}"

- name: install homebrew packages
  homebrew:
    update_homebrew: yes
    name: "{{ item }}"
    state: present
  with_items: "{{ homebrew_packages }}"

- name: install hombrew cask apps
  homebrew_cask:
    name: "{{ item }}"
  with_items: "{{ homebrew_cask_apps }}"

- name: install pip packages
  become: yes
  pip:
    name: "{{ item }}"
    state: present
  with_items: "{{ pip_packages }}"

- name: install gem packages
  become: yes
  gem:
    name: "{{ item }}"
    state: present
  with_items: "{{ gem_packages }}"

