---
- name: add homebrew taps
  homebrew_tap:
    name: "{{ item }}" 
    state: present
  with_items: "{{ homebrew_taps }}"

- name: install homebrew packages 
  homebrew:
    update_homebrew: yes
    name: "{{ item }}"
    state: present
  with_items: "{{ homebrew_packages }}"

- name: install hombrew cask apps
  homebrew_cask:
    name: "{{ item }}"
  with_items: "{{ homebrew_cask_apps }}"

- name: install pip packages
  pip: 
    name: "{{ item }}" 
    state: present
  with_items: "{{ pip_packages }}"

- name: install gem packages
  gem: 
    name: "{{ item }}" 
    state: present
  with_items: "{{ gem_packages }}"

